"""Add incident closure fields

Revision ID: e1c21ccaea86
Revises: 85bbd9d419bd
Create Date: 2026-09-21 09:49:39.761217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1c21ccaea86'
down_revision: Union[str, None] = '85bbd9d419bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('incidents', sa.Column('closed_by', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('resolution_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'resolution_note')
    op.drop_column('incidents', 'closed_by')
    op.drop_column('incidents', 'closed_at')
    # ### end Alembic commands ###
